/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sudosu.controleestoque.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.sudosu.controleestoque.domain.Retirada;
import br.com.sudosu.controleestoque.servicos.BancoServicos;
import br.com.sudosu.controleestoque.servicos.ServicosFactory;

/**
 *
 * @author Vinicius.Vianna
 */
public class TelaListaRetirada extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListaRetirada
     */
    public TelaListaRetirada() {
        initComponents();
        preencherTabela();
    }
    
     DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"RETIRADA", "CONTEUDO", "LOCAL", "ENVIADO POR", "RECEBIDO POR"});

    public void preencherTabela() {
        try {

            BancoServicos bs = ServicosFactory.getBancoServicos();
            ArrayList<Retirada> retirada = new ArrayList<>();

            retirada = bs.buscarRetirada();

            for (int i = 0; i < retirada.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(retirada.get(i).getIdRetirada()),
                    String.valueOf(retirada.get(i).getConteudo()),
                    String.valueOf(retirada.get(i).getLocal()),
                    String.valueOf(retirada.get(i).getEnviado()),
                    String.valueOf(retirada.get(i).getRecebido())
                });
            }//fecha for
            tblRetirada.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    public void limparTabela() {
        dtm.setNumRows(0);
    }//fecha metodo

    public void filtrarTabela() {
        try {
            if (tfPesquisa.getText().isEmpty()) {
                preencherTabela();
            } else {
                BancoServicos bs = ServicosFactory.getBancoServicos();
                String pesquisa = (String) tfPesquisa.getText();
                String query;

//                if (pesquisa.equals("Patrimonio")) {
                    query = " where id_retirada = " + pesquisa;
//                } else {
//                    query = " where chamado like '%" + tfPesquisa.getText() + "%'";
//                }//fecha else

                ArrayList<Retirada> retirada = new ArrayList<>();
                retirada = bs.filtrarRetirada(query);

                for (int i = 0; i < retirada.size(); i++) {
                     dtm.addRow(new String[]{
                    String.valueOf(retirada.get(i).getIdRetirada()),
                    String.valueOf(retirada.get(i).getConteudo()),
                    String.valueOf(retirada.get(i).getLocal()),
                    String.valueOf(retirada.get(i).getEnviado()),
                    String.valueOf(retirada.get(i).getRecebido())
                });
                }//fecha for
                tblRetirada.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Filtrar! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRetirada = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Transferência de Bkup");
        setFrameIcon(null);

        jLabel1.setText("Numero da Retirada ");

        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sudosu/controleestoque/imagens/icon_refresh.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(64, 64));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblRetirada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRetirada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 815, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        limparTabela();
        filtrarTabela();
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       limparTabela();
       preencherTabela();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRetirada;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
