/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sudosu.controleestoque.view;

import br.com.sudosu.controleestoque.domain.OrdemServico;
import br.com.sudosu.controleestoque.servicos.BancoServicos;
import br.com.sudosu.controleestoque.servicos.ServicosFactory;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius.Vianna
 */
public class TelaListaOrdemServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListaOrdemServico
     */
    public TelaListaOrdemServico() {
        initComponents();
        preencherTabela();
    }
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"CÓDIGO", "PATRIMONIO", "CHAMADO", "CONTATO", "DEFEITO", "TECNICO"});

    public void preencherTabela() {
        try {

            BancoServicos bs = ServicosFactory.getBancoServicos();
            ArrayList<OrdemServico> servico = new ArrayList<>();

            servico = bs.buscarOrdemServicos();

            for (int i = 0; i < servico.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(servico.get(i).getIdServico()),
                    String.valueOf(servico.get(i).getPatrimonio()),
                    String.valueOf(servico.get(i).getChamado()),
                    String.valueOf(servico.get(i).getContato()),
                    String.valueOf(servico.get(i).getDefeito()),
                    String.valueOf(servico.get(i).getTecnico())
                });
            }//fecha for
            tblSrevico.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    public void limparTabela() {
        dtm.setNumRows(0);
    }//fecha metodo

    public void filtrarTabela() {
        try {
            if (tfPesquisa.getText().isEmpty()) {
                preencherTabela();
            } else {
                BancoServicos bs = ServicosFactory.getBancoServicos();
                String pesquisa = (String) cbBusca.getSelectedItem();
                String query;

                if (pesquisa.equals("Patrimonio")) {
                    query = " where patrimonio like '%" + tfPesquisa.getText() + "%'";
                } else {
                    query = " where chamado like '%" + tfPesquisa.getText() + "%'";
                }//fecha else

                ArrayList<OrdemServico> servico = new ArrayList<>();
                servico = bs.filtrarOS(query);

                for (int i = 0; i < servico.size(); i++) {
                    dtm.addRow(new String[]{
                        String.valueOf(servico.get(i).getIdServico()),
                        String.valueOf(servico.get(i).getPatrimonio()),
                        String.valueOf(servico.get(i).getChamado()),
                        String.valueOf(servico.get(i).getContato()),
                        String.valueOf(servico.get(i).getDefeito()),
                        String.valueOf(servico.get(i).getTecnico())
                    });
                }//fecha for
                tblSrevico.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Filtrar! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSrevico = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        cbBusca = new javax.swing.JComboBox<>();
        tfPesquisa = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle(" Lista Ordem de Servico");
        setFrameIcon(null);

        tblSrevico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSrevico);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_refresh.png"))); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(64, 64));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        cbBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patrimonio", "Chamado" }));

        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });
        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(cbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );

        setBounds(0, 0, 848, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        limparTabela();
        filtrarTabela();
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased


    }//GEN-LAST:event_tfPesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSrevico;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
