/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sudosu.controleestoque.view;

import br.com.sudosu.controleestoque.servicos.BancoServicos;
import br.com.sudosu.controleestoque.servicos.ServicosFactory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Vinicius.Vianna
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);

//        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/iconeCTRL.png"));
//        this.setIconImage(imagemTitulo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menArqEquip = new javax.swing.JMenuItem();
        menArqBkup = new javax.swing.JMenuItem();
        menArqRetiBkup = new javax.swing.JMenuItem();
        menArqServico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menArqListEquip = new javax.swing.JMenuItem();
        menArquListBkup = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRelEquip = new javax.swing.JMenuItem();
        menRelBkup = new javax.swing.JMenuItem();
        menuRelRelatorio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menOpSair = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TBSA - Controle de Estoque");
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(0, 0));

        dpPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivos");

        menArqEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menArqEquip.setText("Controle de Equipamentos");
        menArqEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArqEquipActionPerformed(evt);
            }
        });
        jMenu1.add(menArqEquip);

        menArqBkup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menArqBkup.setText("Controle de Bkups");
        menArqBkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArqBkupActionPerformed(evt);
            }
        });
        jMenu1.add(menArqBkup);

        menArqRetiBkup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menArqRetiBkup.setText("Transferência de Bkup");
        menArqRetiBkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArqRetiBkupActionPerformed(evt);
            }
        });
        jMenu1.add(menArqRetiBkup);

        menArqServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menArqServico.setText("Ordem de Serviço");
        menArqServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArqServicoActionPerformed(evt);
            }
        });
        jMenu1.add(menArqServico);
        jMenu1.add(jSeparator1);

        menArqListEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menArqListEquip.setText("Lista de Equipamentos");
        menArqListEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArqListEquipActionPerformed(evt);
            }
        });
        jMenu1.add(menArqListEquip);

        menArquListBkup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        menArquListBkup.setText("Lista de Bkups");
        menArquListBkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArquListBkupActionPerformed(evt);
            }
        });
        jMenu1.add(menArquListBkup);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Lista de Ordem de serviço");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Lista de Transferências de Bkup");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        menRel.setText("Relatórios");

        menRelEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menRelEquip.setText("Relatório de Equipamentos");
        menRelEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelEquipActionPerformed(evt);
            }
        });
        menRel.add(menRelEquip);

        menRelBkup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menRelBkup.setText("Relatório de Bkup");
        menRelBkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelBkupActionPerformed(evt);
            }
        });
        menRel.add(menRelBkup);

        menuRelRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.ALT_MASK));
        menuRelRelatorio.setText("Filtro de Relatório");
        menuRelRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelRelatorioActionPerformed(evt);
            }
        });
        menRel.add(menuRelRelatorio);

        jMenuBar1.add(menRel);

        jMenu3.setText("Ajuda");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Opções");

        menOpSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menOpSair.setText("Sair");
        menOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpSairActionPerformed(evt);
            }
        });
        jMenu4.add(menOpSair);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Desconectar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal)
        );

        setBounds(0, 0, 880, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void menArqListEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArqListEquipActionPerformed
      TelaListaEquipamento listaEquipamento = new TelaListaEquipamento();
      listaEquipamento.setVisible(true);
      dpPrincipal.add(listaEquipamento);
    }//GEN-LAST:event_menArqListEquipActionPerformed

    private void menArqEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArqEquipActionPerformed
        TelaControleEquipamento controleEquipamento = new TelaControleEquipamento();
        controleEquipamento.setVisible(true);
        dpPrincipal.add(controleEquipamento);
    }//GEN-LAST:event_menArqEquipActionPerformed

    private void menOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da aplicação?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }//fecha if

     }//GEN-LAST:event_menOpSairActionPerformed

    private void menArqBkupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArqBkupActionPerformed
        TelaControleBkup bkup = new TelaControleBkup();
        bkup.setVisible(true);
        dpPrincipal.add(bkup);
    }//GEN-LAST:event_menArqBkupActionPerformed

    private void menArqServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArqServicoActionPerformed
        TelaOrdemServico ordemServico = new TelaOrdemServico();
        ordemServico.setVisible(true);
        dpPrincipal.add(ordemServico);
    }//GEN-LAST:event_menArqServicoActionPerformed

    private void menArqRetiBkupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArqRetiBkupActionPerformed
        TelaRetiradaBkup retiradaBkup = new TelaRetiradaBkup();
        retiradaBkup.setVisible(true);
        dpPrincipal.add(retiradaBkup);
    }//GEN-LAST:event_menArqRetiBkupActionPerformed

    private void menRelEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelEquipActionPerformed
       BancoServicos bs = ServicosFactory.getBancoServicos();
        try {
            bs.imprimirRelatorioEquipamento();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível emitir relatório!"+ex.getMessage());
        }
    }//GEN-LAST:event_menRelEquipActionPerformed

    private void menRelBkupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelBkupActionPerformed
        BancoServicos bs = ServicosFactory.getBancoServicos();
        try {
            bs.imprimirRelatorioBkup();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível emitir relatório!"+e.getMessage());
        }
    }//GEN-LAST:event_menRelBkupActionPerformed

    private void menArquListBkupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArquListBkupActionPerformed
       TelaListaBkup bkup = null;
        try {
            bkup = new TelaListaBkup();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       bkup.setVisible(true);
       dpPrincipal.add(bkup);
    }//GEN-LAST:event_menArquListBkupActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaListaOrdemServico servico = new TelaListaOrdemServico();
        servico.setVisible(true);
        dpPrincipal.add(servico);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        dpPrincipal.add(sobre);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaListaRetirada listaRetirada = new TelaListaRetirada();
        listaRetirada.setVisible(true);
        dpPrincipal.add(listaRetirada);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuRelRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelRelatorioActionPerformed
        BancoServicos bs = ServicosFactory.getBancoServicos();
        try {
            bs.filtrarRelatorioEquipamento();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRelRelatorioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       TelaLogin login = new TelaLogin();
       login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menArqBkup;
    public static javax.swing.JMenuItem menArqEquip;
    public static javax.swing.JMenuItem menArqListEquip;
    private javax.swing.JMenuItem menArqRetiBkup;
    private javax.swing.JMenuItem menArqServico;
    private javax.swing.JMenuItem menArquListBkup;
    private javax.swing.JMenuItem menOpSair;
    private javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelBkup;
    public static javax.swing.JMenuItem menRelEquip;
    public static javax.swing.JMenuItem menuRelRelatorio;
    // End of variables declaration//GEN-END:variables
}
