/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sudosu.controleestoque.view;

import br.com.sudosu.controleestoque.domain.Equipamento;
import br.com.sudosu.controleestoque.servicos.BancoServicos;
import br.com.sudosu.controleestoque.servicos.ServicosFactory;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius.Vianna
 */
public class TelaControleEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaControleEquipamento
     */
    public TelaControleEquipamento() {
        initComponents();
    }

    private void cadastrar() {
        Equipamento equip = new Equipamento();

        try {
            equip.setPatrimonio(Integer.parseInt(tfPatrimonio.getText()));
            equip.setDescricao(taDescricao.getText());
            equip.setTipo(tfTipo.getText());
            equip.setQuantidade(Integer.parseInt(tfQuantidade.getText()));

            BancoServicos bancoServicos = ServicosFactory.getBancoServicos();
            bancoServicos.cadastrarEquipamento(equip);

            JOptionPane.showMessageDialog(null, "Equipamento cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Equipamento !" + e.getMessage());
        }//fecha catch
    }//fecha metodo

    private void alterar() {
        Equipamento equip = new Equipamento();

        try {
            equip.setPatrimonio(Integer.parseInt(tfPatrimonio.getText()));
            equip.setDescricao(taDescricao.getText());
            equip.setTipo(tfTipo.getText());
            equip.setQuantidade(Integer.parseInt(tfQuantidade.getText()));

            BancoServicos bs = ServicosFactory.getBancoServicos();
            bs.alterarEquipamento(equip);

            JOptionPane.showMessageDialog(null, "Equipamento alterado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar Equipamento !" + e.getMessage());
        }//fecha catch
    }//fecha metodo

    private void limpar() {
        tfPatrimonio.setText(null);
        tfQuantidade.setText(null);
        tfTipo.setText(null);
        taDescricao.setText(null);
    }//fecha metodo
    
    public ArrayList<Equipamento> filtrarEquipamento(){

        try {
            String busca = JOptionPane.showInputDialog("Digite o patrimonio do equipamento!");
            HashMap filtro = new HashMap();
            filtro.put("", Integer.parseInt(busca));

            BancoServicos bs = ServicosFactory.getBancoServicos();
            String query;
            query = "where patrimonio = " + busca;

            ArrayList<Equipamento> equip = new ArrayList<>();
            equip = bs.filtrarEquipamento(query);

            for (int i = 0; i < equip.size(); i++) {
                tfPatrimonio.setText(busca);
                tfQuantidade.setText(Integer.toString(equip.get(i).getQuantidade()));
                tfTipo.setText(equip.get(i).getTipo());
                taDescricao.setText(equip.get(i).getDescricao());

            }//fehca for
            return equip;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar! " + e.getMessage());
        }//fecha catch
        return null;
    }//fecha metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdiciona = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        tfPatrimonio = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        btnBusca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Controle de Equipamentos");
        setEnabled(false);
        setFrameIcon(null);

        jLabel1.setText("Patrimônio");

        jLabel2.setText("Tipo");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Descrição");

        btnAdiciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sudosu/controleestoque/imagens/icon_add.png"))); // NOI18N
        btnAdiciona.setToolTipText("Adicionar");
        btnAdiciona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdiciona.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sudosu/controleestoque/imagens/icon_edit.png"))); // NOI18N
        btnEditar.setToolTipText("Alterar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setPreferredSize(new java.awt.Dimension(64, 64));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sudosu/controleestoque/imagens/icon_serch.png"))); // NOI18N
        btnBusca.setPreferredSize(new java.awt.Dimension(64, 64));
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tfPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnAdiciona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdiciona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );

        setBounds(0, 0, 508, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_btnAdicionaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        alterar();
        limpar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
       filtrarEquipamento();
    }//GEN-LAST:event_btnBuscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiciona;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfPatrimonio;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
