/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sudosu.controleestoque.view;

import br.com.sudosu.controleestoque.domain.Equipamento;
import br.com.sudosu.controleestoque.servicos.BancoServicos;
import br.com.sudosu.controleestoque.servicos.ServicosFactory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius.Vianna
 */
public class TelaListaEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListaEquipamento
     */
    public TelaListaEquipamento() {
        initComponents();
        preencherTabela();

    }

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"PATRIMÔNIO", "DESCRIÇÃO", "TIPO", "QUANTIDADE"});

    public void preencherTabela() {
        try {
            BancoServicos bs = ServicosFactory.getBancoServicos();
            ArrayList<Equipamento> equipamento = new ArrayList<>();

            equipamento = bs.buscarEquipamento();

            for (int i = 0; i < equipamento.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(equipamento.get(i).getPatrimonio()),
                    String.valueOf(equipamento.get(i).getDescricao()),
                    String.valueOf(equipamento.get(i).getTipo()),
                    String.valueOf(equipamento.get(i).getQuantidade())
                });
            }//fecha for
            tblEquipamento.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    public void filtrar() {
        try {
            if (tfPesquisa.getText().isEmpty()) {
                preencherTabela();
            } else {
                BancoServicos bs = ServicosFactory.getBancoServicos();
                String query;
                query = " where patrimonio like '%" + tfPesquisa.getText() + "%'";

                ArrayList<Equipamento> equip = new ArrayList<>();
                equip = bs.filtrarEquipamento(query);

                for (int i = 0; i < equip.size(); i++) {
                    dtm.addRow(new String[]{
                        String.valueOf(equip.get(i).getPatrimonio()),
                        String.valueOf(equip.get(i).getDescricao()),
                        String.valueOf(equip.get(i).getTipo()),
                        String.valueOf(equip.get(i).getQuantidade())
                    });
                }//fehca for
                tblEquipamento.setModel(dtm);
            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Filtrar! " + e.getMessage());
        }//fecha catch
    }//fecha metodo

    public void limparTabela() {
        dtm.setNumRows(0);
    }//fecha metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipamento = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Equipamento");
        setFrameIcon(null);

        jLabel1.setText("PATRIMÔNIO");

        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });
        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyTyped(evt);
            }
        });

        tblEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEquipamento);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_refresh.png"))); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(64, 64));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 827, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased

    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void tfPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaKeyTyped

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        limparTabela();
        filtrar();
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEquipamento;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
